import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainNav} >
        <ul>
          <Link href='/'>
          <a>Home</a>
          </Link>
          <Link href="/about">
            <a>About</a>
          </Link>
          <Link href="/blog">
            <a>Blogs</a>
          </Link>
          <Link href="/contact">
            <a>Contact</a>
          </Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to FANTASTIC-GIGGLE blogs
        </h1>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn HTML in 2022?</h3>
            <p>HTML is the body of website! lets learn it.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn HTML in 2022?</h3>
            <p>HTML is the body of website! lets learn it.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn HTML in 2022?</h3>
            <p>HTML is the body of website! lets learn it.</p>
          </div>
        </div>


      </main>

    </div>
  )
}
